services:
  bot:
    container_name: ban-bot
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - /root:/root
    environment:
      ban_run_env: prod
      ban_data_dir: /root/ban_data
      ban_stgy_dir: /root/ban-strategies
      ban_db_url: postgresql://postgres:vj459gfn23497gn23@[db]:5432/bantd
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    container_name: ban-db
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'vj459gfn23497gn23'
      POSTGRES_DB: 'bantd'
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 15s
