services:
  banbot:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - /root:/root
    environment:
      ban_run_env: prod
      ban_data_dir: /root/ban_data
      ban_stgy_dir: /root/ban-strategies
      ban_db_url: postgresql://postgres:123@[db]:5432/bantd
      ban_redis_url: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
        restart: true
      db:
        condition: service_healthy
        restart: true
  redis:
    image: redis:7
    volumes:
      - /root/ban_data/redis.conf:/redis.conf
    ports:
      - "127.0.0.1:6679:6379"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/6379; exit $?;'"]
      interval: 2s
      timeout: 2s
      retries: 5
  db:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "127.0.0.1:5632:5432"
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'bantd'
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"]
      interval: 2s
      timeout: 2s
      retries: 5
